### ISSUE TITLE
Warning when starting example

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#1064]
```
(node:17244) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Object.<anonymous> (E:\Source\h5p\h5p-nodejs-library\packages\h5p-mongos3\node_modules\mongodb\lib\operations\operation.js:4:38)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\Source\h5p\h5p-nodejs-library\packages\h5p-mongos3\node_modules\mongodb\lib\operations\execute_operation.js:4:16)
```

**Comment by sr258** [comment]
Must be solved upstream: https://github.com/mongodb/node-mongodb-native/pull/2734
