### ISSUE TITLE
can not install and run

### ISSUE THREAD

**Issue by arashsoftco** [Lumieducation/H5P-Nodejs-library#1106]
hi i can not still install new version 
i git clone a project and run npm i
```
arash@arash-itosoft:~/Desktop/h5p/github$ npm start

> @lumieducation/h5p-monorepo@7.0.1 start /home/arash/Desktop/h5p/github
> npm run start --prefix packages/h5p-examples


> @lumieducation/h5p-examples@7.1.0 start /home/arash/Desktop/h5p/github/packages/h5p-examples
> CACHE=in-memory node build/express.js

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/home/arash/Desktop/h5p/github/packages/h5p-examples/build/express.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @lumieducation/h5p-examples@7.1.0 start: `CACHE=in-memory node build/express.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @lumieducation/h5p-examples@7.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arash/.npm/_logs/2021-02-25T16_14_51_653Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @lumieducation/h5p-monorepo@7.0.1 start: `npm run start --prefix packages/h5p-examples`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @lumieducation/h5p-monorepo@7.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:


```

**Comment by sr258** [comment]
I'm afraid I can't reproduce this. A newly cloned repo with `npm install` can execute `npm start` on my machine. What version of NPM are you using? Try cloning again, maybe there are left-overs in old node_modules directories.

**Comment by arashsoftco** [comment]
@sr258 
v12.18.4
all i do is git clone and npm i && npm start
looks like it needs build of  express package

**Comment by sr258** [comment]
`npm install` should install the dependencies of all packages and also build all packages. You should see the build scripts running at the end of `npm install`. Can you show the output when running it?

**Comment by arashsoftco** [comment]
oh so i guess i had a crached while downloading **Chromium**

**Comment by arashsoftco** [comment]
@sr258 

```
arash@arash-itosoft:~/Desktop/h5p/lates/H5P-Nodejs-library$ npm i

> puppeteer@7.1.0 install /home/arash/Desktop/h5p/lates/H5P-Nodejs-library/node_modules/puppeteer
> node install.js

Downloading Chromium r848005 - 138.2 Mb [=                   ] 4% 1398.4s ERROR: Failed to set up Chromium r848005! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
npm WARN @fimbul/bifrost@0.21.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-config-airbnb@5.11.2 requires a peer of tslint@^5.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fimbul/bifrost@0.21.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-eslint-rules@5.4.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-eslint-rules@5.4.0 requires a peer of typescript@^2.2.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-microsoft-contrib@5.2.1 requires a peer of tslint@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-microsoft-contrib@5.2.1 requires a peer of typescript@^2.1.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-consistent-codestyle@1.16.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@7.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@7.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arash/.npm/_logs/2021-02-25T17_37_45_591Z-debug.log

```

**Comment by arashsoftco** [comment]
@sr258 
problem solved for npm i but still can not start project

npm i :
```

root@bisotuntech:~/h5p/H5P-Nodejs-library# npm i

> husky@4.3.6 install /root/h5p/H5P-Nodejs-library/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> puppeteer@7.1.0 install /root/h5p/H5P-Nodejs-library/node_modules/puppeteer
> node install.js

Downloading Chromium r848005 - 138.2 Mb [====================] 100% 0.0s 
Chromium (848005) downloaded to /root/h5p/H5P-Nodejs-library/node_modules/puppeteer/.local-chromium/linux-848005

> core-js@3.9.0 postinstall /root/h5p/H5P-Nodejs-library/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> husky@4.3.6 postinstall /root/h5p/H5P-Nodejs-library/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm WARN lifecycle @lumieducation/h5p-monorepo@7.0.1~postinstall: cannot run in wd @lumieducation/h5p-monorepo@7.0.1 npx lerna bootstrap && npm run download:content-type-cache && npm run download:h5p (wd=/root/h5p/H5P-Nodejs-library)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2050 packages from 1324 contributors and audited 2027 packages in 59.887s

112 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

```

npm start
```

root@bisotuntech:~/h5p/H5P-Nodejs-library# npm start

> @lumieducation/h5p-monorepo@7.0.1 start /root/h5p/H5P-Nodejs-library
> npm run start --prefix packages/h5p-examples


> @lumieducation/h5p-examples@7.1.0 start /root/h5p/H5P-Nodejs-library/packages/h5p-examples
> CACHE=in-memory node build/express.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/root/h5p/H5P-Nodejs-library/packages/h5p-examples/build/express.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @lumieducation/h5p-examples@7.1.0 start: `CACHE=in-memory node build/express.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @lumieducation/h5p-examples@7.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-25T19_03_12_530Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @lumieducation/h5p-monorepo@7.0.1 start: `npm run start --prefix packages/h5p-examples`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @lumieducation/h5p-monorepo@7.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-25T19_03_12_557Z-debug.log

```

**Comment by sr258** [comment]
The problem lies here: npm WARN lifecycle @lumieducation/h5p-monorepo@7.0.1~postinstall: cannot run in wd @lumieducation/h5p-monorepo@7.0.1 npx lerna bootstrap && npm run download:content-type-cache && npm run download:h5p (wd=/root/h5p/H5P-Nodejs-library)

The NPM postinstall script can‘t execute as root. You have to do this as a regular user (I wouldn‘t recommend developing as root anyway). Alternatively there seem to be workarounds, e.g. the one discussed here: https://github.com/pre-commit/pre-commit/issues/1272
You can also simply try running npm run postinstall

**Comment by arashsoftco** [comment]
thanks great it works

**Comment by sr258** [comment]
A pleasure!
