### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by programmeddeath1** [Lumieducation/h5p-nodejs-library#1971]
On Running npm install and start its failing with below error

```
H5P-Nodejs-library/packages/h5p-mongos3/node_modules/whatwg-url/lib/encoding.js:2
const utf8Encoder = new TextEncoder();


ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (H5P-Nodejs-library/packages/h5p-mongos3/node_modules/whatwg-url/lib/encoding.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (H5P-Nodejs-library/packages/h5p-mongos3/node_modules/whatwg-url/lib/url-state-machine.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

**Comment by sr258** [comment]
What‘s your OS, Node version and NPM version?

**Comment by sr258** [comment]
@programmeddeath1 I've tried a fresh clone on a system using Node 17 and things work fine. Please check whether you've got at least Node 16 and NPM 7.
